import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/globals/header/component";
import {getPayload} from "payload";
import config from '@payload-config'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const payload = await getPayload({config});
const header = await payload.findGlobal({
    slug: 'header'
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}>
            
            <h1 className="text-4xl text-center">Work in progress!</h1>
            <HeaderComponent header={header}/>
            
            {children}
        
        </body>
    </html>
    );
}
